# Chapter 10. Building Neural Networks with PyTorch

PyTorch is a deep learning library for building and training neural networks.

Like NumPy, it provides multidimensional arrays for numerical computation. In addition, it supports automatic differentiation and hardware acceleration.

## PyTorch Fundamentals

The core data structure in PyTorch is the tensor.

A tensor is a multidimensional array with a shape and data type, similar to a NumPy array. Unlike NumPy arrays, tensors can use hardware accelerators and support automatic differentiation.

### PyTorch Tensors

In [6]:
import torch

X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]])

print(X)

tensor([[1., 4., 7.],
        [2., 3., 6.]])


Like NumPy arrays, tensors have a shape and a data type.

In [13]:
print("Shape:", X.shape)
print("\nData type:", X.dtype)

Shape: torch.Size([2, 3])

Data type: torch.float32


Tensor indexing and slicing work similarly to NumPy.

In [22]:
print(X[0, 1])
print(X[:, 1])

tensor(4.)
tensor([4., 3.])


PyTorch supports elementwise operations, reductions, and matrix multiplication.

In [27]:
10 * (X + 1.0) # itemwise addition and multiplication

tensor([[20., 50., 80.],
        [30., 40., 70.]])

In [29]:
X.exp() # itemwise exponential

tensor([[   2.7183,   54.5981, 1096.6332],
        [   7.3891,   20.0855,  403.4288]])

In [31]:
X.mean()

tensor(3.8333)

In [35]:
X.max(dim=0) # max values along dimension 0 (i.e., max value per column)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [37]:
X @ X.T # matrix transpose and matrix multiplication

tensor([[66., 56.],
        [56., 49.]])

Tensors can be converted to NumPy arrays, and NumPy arrays can be converted to tensors.

PyTorch uses `float32` by default for floating-point tensors, while NumPy usually uses `float64`.

In [54]:
import numpy as np

print("Tensor converted to a NumPy array:")
X.numpy()

Tensor converted to a NumPy array:


array([[1., 4., 7.],
       [2., 3., 6.]], dtype=float32)

In [58]:
print("Tensor created from a NumPy array:")
torch.tensor(np.array([[1., 4., 7.], [2., 3., 6.]]))

Tensor created from a NumPy array:


tensor([[1., 4., 7.],
        [2., 3., 6.]], dtype=torch.float64)

Using `float32` is common in deep learning because it uses less memory and is generally faster than `float64`, while providing enough precision for most neural network tasks.

PyTorch supports in-place operations, which modify an existing tensor directly.

These operations end with an underscore, such as `relu_()` or `zero_()`.

In [68]:
X[:, 1] = -99

print("After modifying the second column:")
X

After modifying the second column:


tensor([[  1., -99.,   7.],
        [  2., -99.,   6.]])

In [70]:
X.relu_()

print("After applying ReLU in place:")
X

After applying ReLU in place:


tensor([[1., 0., 7.],
        [2., 0., 6.]])

In-place operations can save memory, but they should be used carefully when working with autograd because modifying tensors needed for backpropagation can cause errors.